# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Angel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('pic', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('url', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'angel_data',
            },
        ),
        migrations.CreateModel(
            name='CompaniesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('image_url', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('joined', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('location', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('market', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('website', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('employees', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('stage', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('total_raised', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'companies_data',
            },
        ),
        migrations.CreateModel(
            name='ListSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'list_selection',
            },
        ),
        migrations.CreateModel(
            name='LocationSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'location_selection',
            },
        ),
        migrations.CreateModel(
            name='MarketSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'market_selection',
            },
        ),
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'post_type',
            },
        ),
        migrations.CreateModel(
            name='Schedular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('schedule_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lists', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='custom_admin.ListSector')),
                ('location', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='custom_admin.LocationSector')),
                ('market', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='custom_admin.MarketSector')),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'selection_types',
            },
        ),
        migrations.CreateModel(
            name='StageSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'stage_selection',
            },
        ),
        migrations.CreateModel(
            name='TypeSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'type_selection',
            },
        ),
        migrations.AddField(
            model_name='schedular',
            name='selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='custom_admin.Selection'),
        ),
        migrations.AddField(
            model_name='schedular',
            name='stage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='custom_admin.StageSector'),
        ),
        migrations.AddField(
            model_name='schedular',
            name='types',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='custom_admin.TypeSector'),
        ),
        migrations.AddField(
            model_name='companiesdata',
            name='lists',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='custom_admin.ListSector'),
        ),
        migrations.AddField(
            model_name='companiesdata',
            name='locationfil',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='custom_admin.LocationSector'),
        ),
        migrations.AddField(
            model_name='companiesdata',
            name='marketfil',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='custom_admin.MarketSector'),
        ),
        migrations.AddField(
            model_name='companiesdata',
            name='stagefil',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='custom_admin.StageSector'),
        ),
        migrations.AddField(
            model_name='companiesdata',
            name='types',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='custom_admin.TypeSector'),
        ),
        migrations.AddField(
            model_name='angel',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='custom_admin.PostType'),
        ),
    ]
